version: '3'
services:
  frontend:
    stdin_open: true
    container_name: frontend_desafio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
